var endent = require('endent')

module.exports = endent`
  {
    "name": "boowa-blog",
    "version": "1.0.0",
    "description": "A blog generated by boowa",
    "main": "index.js",
    "scripts": {
      "start": "bankai start index.js",
      "build": "bankai build index.js"
    },
    "author": "",
    "license": "MIT",
    "dependencies": {
      "bankai": "9.4.1",
      "brfs": "^1.4.3",
      "choo": "^6.8.0",
      "endent": "^1.1.1",
      "detect-indent": "^5.0.0",
      "github-markdown-css": "^2.10.0",
      "nanocomponent": "^6.5.0",
      "prismjs": "^1.10.0",
      "sheetify": "^7.2.0",
      "sheetify-sass": "^2.0.0"
    },
    "browserify": {
      "transform": [
        [
          "brfs"
        ],
        [
          "sheetify"
        ]
      ]
    },
    "sheetify": {
      "transform": [
        [
          "sheetify-sass"
        ]
      ]
    }
  }
`
